// Auto-generated by scripts/generate-app-version.js — do not edit manually
export const APP_VERSION = '0.0.0';
export const APP_BUILD_ID = '0.0.0-1788465502893';
export const APP_BUILT_AT = '2026-09-03T19:58:22.893Z';
