// Auto-generated by scripts/generate-app-version.js — do not edit manually
export const APP_VERSION = '0.0.0';
export const APP_BUILD_ID = '0.0.0-1783461480229';
export const APP_BUILT_AT = '2026-07-07T21:58:00.229Z';
