// Auto-generated by scripts/generate-app-version.js — do not edit manually
export const APP_VERSION = '0.0.0';
export const APP_BUILD_ID = '0.0.0-1791049343864';
export const APP_BUILT_AT = '2026-10-03T17:42:23.864Z';
